Add hdps::fromStdVector() to fix errors about missing Qt constructors
Added `hdps::fromStdVector(const std::vector<ValueType>&)`, fixing three errors on the CI, which were triggered by the fact that the CI still uses an old version of Qt (5.12.4).

From xcode10.3:

> ImageViewerPlugin.cpp:77:24: error: no matching constructor for initialization of 'QVector<uint>'

From GCC9:

> PointsLayer.cpp:59:122: error: no matching function for call to ‘QStringList::QStringList(std::vector<QString>::const_iterator, std::vector<QString>::const_iterator)’

https://travis-ci.com/github/bldrvnlw/conan-ImageViewerPlugin/jobs/367085106#L8362

https://travis-ci.com/github/bldrvnlw/conan-ImageViewerPlugin/jobs/368253954#L1620