Add missing #include <QKeyEvent>, necessary for Qt 5.14.2
Fixes compilation errors from Visual C++ 2019, including:

> ViewerWidget.cpp(81,49): error C2440: 'static_cast': cannot convert from 'QEvent *' to 'QKeyEvent *'
> ViewerWidget.cpp(81,20): message : Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
  ...
> SelectionLayer.cpp(640,11): error C3536: 'keyEvent': cannot be used before it is initialized